version: '3.7'

services:
  dev_postgres:
    image: postgres:latest
    container_name: dev_postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - dev_pgdata:/var/lib/postgresql/data
    networks:
      - postgres_network
  
  test_postgres:
    image: postgres:latest
    container_name: test_postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - test_pgdata:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  dev_pgdata:
  test_pgdata:

networks:
  postgres_network:
